version: "3.5"

services:
  api:
    build:
      context: .
    env_file: ".env"
    environment:
      - LOG_LEVEL=10
      - TESTING=1
    ports:
      - "9002:9002"
    restart: always
    volumes: 
      - './images:/images'
      - './data:/data'
